.TH NBWORKS_DELNAME 3  2013-05-01 "" "Linux Programmer's Manual"
.SH NAME
nbworks_delname \- delete NetBIOS name
.SH SYNOPSIS
.nf
.B #include <nbworks.h>
.sp
.BI "int"
.br
.BI "  nbworks_delname(nbworks_namestate_p " handle ");"
.fi
.SH DESCRIPTION
The \fBnbworks_regname\fP() function deletes a NetBIOS name. It
interacts with the nbworks multiplexing daemon to accomplish this
task.
.PP
The argument \fIhandle\fP is the name handle returned by a previous
successfull call to \fBnbworks_regname\fP().
.SH "RETURN VALUE"
This function returns a positive number if is succeds, zero if it
fails or a negative number if an error occurs.
.PP
In case of error, you should check \fInbworks_errno\fP for more
information.
.SH "SEE ALSO"
.BR nbworks (7),
.BR nbworks_regname (3),
