.TH NBWORKS_LIBINIT 3  2013-05-01 "" "Nbworks Manual"
.SH NAME
nbworks_libinit \- initialize nbworks library
.SH SYNOPSIS
.nf
.B #include <nbworks.h>
.sp
.BI "void"
.br
.BI "  nbworks_libinit(void);"
.fi
.SH DESCRIPTION
The \fBnbworks_libinit\fP() function initializes the internal state
of the nbworks library control data fields. It should be called once after
loading the library, and that call should be before any other calls to
nbworks functions.
.PP
Aditional calls to \fBnbworks_libinit\fP() reset the internal state of
the libraries control structure.
.SH "RETURN VALUE"
This function does not have a return value.
.SH "SEE ALSO"
.BR nbworks (7),
.BR nbworks_libcntl (7),
.BR nbworks_reinit_myIP4address (3)
