.TH NBWORKS_DELNAME 3  2013-05-01 "" "Nbworks Manual"
.SH NAME
nbworks_delname \- delete NetBIOS name
.SH SYNOPSIS
.nf
.B #include <nbworks.h>
.sp
.BI "int"
.br
.BI "  nbworks_delname(nbworks_namestate_p " handle ");"
.fi
.SH DESCRIPTION
The \fBnbworks_regname\fP() function deletes a NetBIOS name. It
interacts with the nbworks multiplexing daemon to accomplish this
task.
.PP
The argument \fIhandle\fP is the name handle returned by a previous
successfull call to \fBnbworks_regname\fP().
.SH "RETURN VALUE"
This function returns a positive number if is succeds, zero if it
fails or a negative number if an error occurs.
.PP
In case of error, you should check \fInbworks_errno\fP for more
information.
.SH NOTES
After a name has been succesfully deleted, all \fIdatagram sessions\fP
extending from that name \fBmust\fP be destroyed or, at the very
least, not used in datagram mode. Using them after their name has been
deleted will produce a segfault in the best case and a fandago on core
in the worst.
.SH "SEE ALSO"
.BR nbworks (7),
.BR nbworks_regname (3)
